import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navBar/NavBar";
import Footer from "./_components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <Navbar></Navbar>
      <body className={inter.className}>{children}</body>
      <Footer></Footer>
    </html>
  );
}
